19:ci: missing pyenv init, reordering, more pyenv info

diff --git a/.github/workflows/ci_asic_19.yaml b/.github/workflows/ci_asic_19.yaml
--- a/.github/workflows/ci_asic_19.yaml
+++ b/.github/workflows/ci_asic_19.yaml
@@ -47,8 +47,14 @@ jobs:
           # mkdir -p "$PYENV_ROOT"
           curl https://pyenv.run | bash
 
+          export PYENV_ROOT="$HOME/dot.pyenv"
+          mkdir -p "$PYENV_ROOT"
+
           # DRY:
           export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
+
+          pyenv init  # dont miss this
+
           eval "$(ssh-agent -s)"
           echo "pyenv ssh-agent eval succeeded."
           echo "Pre-update pyenv version:"
@@ -56,6 +62,7 @@ jobs:
           python --version
 
           pyenv update \
+              || echo "err code: $?"
               || :  # A non-critical step that may fail. FIXME.
           # Can be slow:
           pyenv install $PYTHON_VERSION
@@ -65,12 +72,10 @@ jobs:
 
           echo "Done installing pyenv"
 
-          export PYENV_ROOT="$HOME/dot.pyenv"
-          mkdir -p "$PYENV_ROOT"
-
           # Set up environment for the next steps
+
+          echo "export PYENV_ROOT=\"$PYENV_ROOT\"" >> "$GITHUB_ENV"
           echo '
-            export PYENV_ROOT="$HOME/dot.pyenv"
             export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
           ' >> "$GITHUB_ENV"
           # The "$GITHUB_ENV" is automatically sourced in the next steps
@@ -90,9 +95,19 @@ jobs:
           echo 'debug2'
           env || :
           echo 'debug3'
-          pyenv version
+          pyenv version || : # Why fails?
 
           python --version
+
+          # more information about the environment
+          pyenv global
+          pyenv versions
+          pyenv version-file
+          pyenv which python3
+          pyenv exec echo "$(python3 --version)"
+
+
+
           # All future steps need to start with:
           # set -eux ; eval "$(ssh-agent -s)"
 
