gha-flowv0.0.10: Make GITHUB_ENV safer (to prevent failure)

diff --git a/.github/workflows/ci_asic_19.yaml b/.github/workflows/ci_asic_19.yaml
--- a/.github/workflows/ci_asic_19.yaml
+++ b/.github/workflows/ci_asic_19.yaml
@@ -15,10 +15,10 @@ jobs:
 
     steps:
 
-      - name: Prepare (to be moved to a docker image)
-        # see also : https://gist.github.com/jprjr/7667947
+      - name: Prepare environment: pyenv + ubuntu (to be moved to a docker image)
         run: |
           set -eux
+          # see also : https://gist.github.com/jprjr/7667947
 
           export PYTHON_VERSION=3.12.3
           # Yosys says it is tested on 3.6.
@@ -49,8 +49,14 @@ jobs:
           # DRY:
           export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
           eval "$(ssh-agent -s)"
+          echo "pyenv ssh-agent eval succeeded."
+          echo "Pre-update pyenv version:"
+          pyenv version
+          python --version
 
-          pyenv update || :  # May fail, but not too bad. FIXME.
+          pyenv update \
+              || :  # A non-critical step that may fail. FIXME.
+          # Can be slow:
           pyenv install $PYTHON_VERSION
           pyenv global $PYTHON_VERSION
           # pyenv shell $PYTHON_VERSION
@@ -58,15 +64,17 @@ jobs:
 
           echo "Done installing pyenv"
 
-
-          echo '
           export PYENV_ROOT="$HOME/dot.pyenv"
           mkdir -p "$PYENV_ROOT"
-          export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
-          eval "$(ssh-agent -s)"
-          pyenv version
-          python --version
-          ' >> "$GITHUB_ENV"
+
+          # Set up environment for the next steps
+          echo "
+            export PYENV_ROOT=\"$HOME/dot.pyenv\"
+            export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
+            eval \"$(ssh-agent -s)\"
+            # pyenv version
+            # python --version
+          " >> "$GITHUB_ENV"
           # The "$GITHUB_ENV" is automatically sourced in the next steps
 
       - name: Test use of pyenv
